Create controllers: Questions, Answers
AlkP/sof pull request #4
Opened 2017-10-19 12:13 UTC by AlkP

2017-10-19 17:06 UTC, vkurennov requested changes

2017-10-19 17:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
Нужно свазять с вопросом

2017-10-19 17:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :question_id)
question_id не передается в параметрах, он приходит в url, здесь его быть не должно

2017-10-19 17:06 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @answers = Answer.where('question_id = ? ', @question.id)
Так не принято писать, нужно работать через ассоции: `@question.answers`, ассоциаиции для этого и существуют

2017-10-19 17:06 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { id: answer, answer: { question_id: question, body: "NewAnswer" } } }
question_id не передается в параметрах answer, он должен передаваться в params, т.к. это часть url

2017-10-19 17:06 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: { question_id: question, body: 'NewAnswer' } } }.to change(Answer, :count).by(1)
question_id не передается в параметрах answer, он должен передаваться в params, т.к. это часть url
И тут нужно проверить, что ответ связыватся с вопросом. Это можно сделать прямо в change через ассоциации вопроса

2017-10-19 17:06 UTC, vkurennov commented on config/routes.rb
> +  resources :answers
В требованиях к заданию сказано "Ресурс "ответы" должен быть вложенным в ресурс "вопросы", чтобы в контроллере можно было определить родительский вопрос и создать ответ для него." У тебя они не вложены

2017-10-20 08:25 UTC, vkurennov requested changes

2017-10-20 08:25 UTC, vkurennov commented on .gitignore
> +db/*.sqlite3
А ты что, используешь sqlite? Срочно меняй на postgres, вся разработка ведется на нем.

2017-10-20 08:25 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    set_question
Не нужно никаких методов для этого писать. И не нужно связывать по id, загружаешь вопрос по question_id и затем создаешь ответ через его ассоциации.

2017-10-20 08:25 UTC, vkurennov commented on app/models/answer.rb
> +  validates :question, presence: true
Еще раз: не нужно валидировать ассоциации belongs_to, это рельсы делают автоматом. И не нужно тестировать такую валидацию, если ее удаляешь

2017-10-20 08:25 UTC, vkurennov commented on config/routes.rb
> +  resources :answers
Не нужно снова писать это вне questions, если нужно, чтобы для части роутов не использовалась вложенность, примени опцию [shallow: true](http://guides.rubyonrails.org/routing.html#nested-resources) (см. раздел 2.7.2)

2017-10-20 08:25 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: { body: 'NewAnswer' } } }.to change(Answer, :count).by(1)
Тут в change надо проверить, что ответ связывается с вопросом. Это можно сделать через ассоциации вопроса

2017-10-20 09:26 UTC, AlkP commented on .gitignore
> +db/*.sqlite3
проблема с работой, я работаю в банке и немного строго: могу поставить рубимайн, но не могу поставить постгрес, тут такой вариант, что я на работе использую windows и sqlite3, а дома xubuntu и postgres. Все сложно :)

2017-10-20 15:54 UTC, vkurennov approved these changes

2017-10-20 15:54 UTC, vkurennov commented on .gitignore
> +db/*.sqlite3
ок, это уважительная причина :-)

2017-10-20 15:54 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: { body: nil } } }.to_not change(question.answers, :count)
Здесь как раз не нужно было менять. Надо оставить Answer в change, т.к. важно, что не создан вообще никакой ответ, вне зависимости от его связей

2017-10-20 16:05 UTC, merged