Feature05
AlkP/sof pull request #5
Opened 2017-10-23 18:42 UTC by AlkP

2017-10-24 08:49 UTC, vkurennov requested changes

2017-10-24 08:49 UTC, vkurennov commented on app/views/answers/new.html.haml
> += form_for @answer, url: question_answers_path(@question) do |f|
Тут не нужно url задавать, надо как массив для вложенного ресурса задавать: `[@question,  @answer]`

2017-10-24 08:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Форма у нас должна быть на странцие вопроса, вот эту страницу и надо рендерить.

2017-10-24 08:49 UTC, vkurennov commented on app/views/answers/_form.html.haml
> += form_for @answer do |f|
Нужен вывод ошибок валидации

2017-10-24 08:49 UTC, vkurennov commented on app/views/answers/_index.html.haml
> += link_to 'Answer the Question', new_question_answer_path(@question)
Где же вывод ответов?

2017-10-24 08:49 UTC, vkurennov commented on app/views/answers/new.html.haml
> +%p New for '#{@question.title}' Answer
Этот вид не нужен, форма должна быть на странице вопроса

2017-10-24 08:49 UTC, vkurennov commented on app/views/answers/show.html.haml
> +%h3
Нам не нужен этот вид, все ответы отображаются на странице вопроса

2017-10-24 08:49 UTC, vkurennov commented on app/views/answers/show.html.haml
> +- if @answer.user == current_user
1. Лучше сравнивать по user_id, чтобы не тянуть ассоциацию из базы
2. такое сравнение нам потребуется еще не раз, лучше вынести его в метод `User#author_of?`

2017-10-24 08:49 UTC, vkurennov commented on app/views/questions/_form.html.haml
> += form_for @question do |f|
Нужен вывод ошибок валидации

2017-10-24 08:49 UTC, vkurennov commented on app/views/questions/index.html.haml
> += link_to 'Ask Question', new_question_path
Здесь должен быть вывод существующих вопросов, иначе, как их посмотреть?

2017-10-24 08:49 UTC, vkurennov commented on app/views/questions/show.html.haml
> +- if @question.user == current_user
Замени на `User#author_of?`

2017-10-24 08:49 UTC, vkurennov commented on app/views/questions/show.html.haml
> +  Question: '#{@question.title}'
А тело вопроса как посмотреть?

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/answer/create_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully created.'
Нужно проверить, что текст ответа появился на странице

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/answer/create_answer_spec.rb
> +feature 'Create answer', %q{
Нужен тест на невалидный ответ, проверить, что система выводит ошибки валидации

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/answer/destroy_answer_spec.rb
> +    expect(page).to have_link('Destroy Answer', href: answer_path(answer))
Это лишнее, т.к. далее ты кликаешь по этой ссылке и таким образом проверяешь ее наличие.

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/answer/destroy_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully destroyed.'
Надо проверить, что ответа больше нет на странице

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/answer/show_answer_spec.rb
> +    visit answer_path(answer)
Тут другой сценарий. Ответы должны быть на странице вопроса

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
Нужен тест на невалидный вопрос, проверить, что система выводит ошибки валидации

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Надо проверить, что заголовок и тело вопроса есть на странице

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/questions/destroy_question_spec.rb
> +    expect(page).to have_link('Destroy Question', href: question_path(question))
Лишняя проверка

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/questions/destroy_question_spec.rb
> +    expect(page).to have_content 'Your question successfully destroyed.'
Надо проверить, что вопроса больше нет на странице

2017-10-24 08:49 UTC, vkurennov commented on app/views/questions/show.html.haml
> += render 'answers/index'
По заданию, на этой же странице должна быть форма для создания ответа. Где она?

2017-10-24 08:49 UTC, vkurennov commented on spec/acceptance/questions/update_question_spec.rb
> +feature 'Update question', %q{
Про редактирование вопроса и ответа в задании ничего нет. Не стоит делать лишнюю работу, задание и так объемное. И вообще, если чего-то нет в задании, значит, это пока не стоит делать.

2017-10-24 08:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Нужно проверить, что ответ связывается с залогиненным юзером.

2017-10-24 08:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора и для не-автора

2017-10-24 08:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Надо проверить, что вопрос связывается с залогиненным юзером.

2017-10-24 08:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора и для не-автора

2017-10-24 13:48 UTC, AlkP commented on app/views/answers/_form.html.haml
> += form_for @answer do |f|
не понимаю, а зачем здесь добавлять есть ошибки выводятся в application.html.haml - = render 'layouts/alert'

2017-10-25 08:49 UTC, vkurennov commented on app/views/answers/_form.html.haml
> += form_for @answer do |f|
Потому что ошибки надо выводить не через alert. Сгенерируй какой-нибудь ресурс через scaffold (только удали потом) увидишь код, который рельсы добавляют для вывода ошибок валидаций

2017-10-25 09:04 UTC, vkurennov requested changes

2017-10-25 09:04 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [ :index, :show ]
У тебя же больше нет index, show, зачем тогда except?

2017-10-25 09:04 UTC, vkurennov commented on app/controllers/application_controller.rb
> +     if obj.try(:user_id) == current_user.try(:id)
1. В руби с версии 2.3 есть встроенный safe navigation opertor, try - это рельсовое расширение, которое делаеть то же самое. Теперь можно писать так: `obj&.user_id`
2. Этот метод должен быть в модели User, а не в ApplicationController
3. Сравнение и так возвращет логическое значение, т.е. if/else тут не нужен. Введи в консоли `1 == 1`, оно вернет тебе true, без всяких условий. Соответсвенно, в методе нужно просто сравнение, его результат и будет результатом метода.

2017-10-25 09:04 UTC, vkurennov commented on app/views/answers/_form.html.haml
> += form_for @answer do |f|
Так что вывод ошибок добавь

2017-10-25 09:04 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@answer.question)
Нельзя делать редирект, если есть ошибки валидации. Во-первых, у тебя тогда сама информация об ошибках пропадет, а во-вторых, весь текст, который вводил пользователь. И ему придется заново все вводить

2017-10-25 09:04 UTC, vkurennov commented on app/views/questions/_form.html.haml
> += form_for @question do |f|
Не исправлено

2017-10-25 09:04 UTC, vkurennov commented on app/views/questions/show.html.haml
> +- if @question.user == current_user
Используй метод `User#author_of?`

2017-10-25 09:04 UTC, vkurennov commented on app/views/questions/show.html.haml
> += render 'answers/new'
Логичнее форму держать под списком ответов

2017-10-25 09:04 UTC, vkurennov commented on spec/acceptance/answer/create_answer_spec.rb
> +feature 'Create answer', %q{
Не исправлено, где тест на невалидный ответ?

2017-10-25 09:04 UTC, vkurennov commented on spec/acceptance/answer/create_answer_spec.rb
> +  given(:question) { create( :question, title: 'Title', body: 'Body', user_id: user.id )}
Зачем вообще задвать title, body и user, они же у тебя через фабрики должны генерироваться. Указывать надо, когда нужно задать для теста конкретное значение, а когда не важно, смысла нет.

2017-10-25 09:04 UTC, vkurennov commented on spec/acceptance/answer/destroy_answer_spec.rb
> +    answer
чтобы так не писать, используй `given!`, он будет создавать данные до теста

2017-10-25 09:04 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
Где тест?

2017-10-25 09:04 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: { body: 'NewAnswer' } } }.to change(user.answers, :count).by(1)
Да, но так ты теперь не проверяешь, что ответ связывается с вопросом. А надо и то и другое проверить

2017-10-25 09:04 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with not log in user' do
Тут другой контекст еще нужен: юзер залогинен, но он не автор ответа

2017-10-25 09:04 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'without sign in user' do
Тут другой контекст еще нужен: юзер залогинен, но он не автор вопроса

2017-10-25 09:04 UTC, vkurennov commented on spec/factories/questions.rb
> +    title
Добавь сюда еще строку user, у тебя автоматом будет создавться user через одноименную фабрику и связываться с вопросом

2017-10-25 15:22 UTC, vkurennov requested changes

2017-10-25 15:22 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    unless params[:answer][:body] == ""
Ну что это такое? У тебя есть валидации в модели, вот их и используй. При вызове save они будут запускаться. Единственное, что нужно делать не редирект, а рендер страницы вопроса, если есть ошибки валидации

2017-10-25 15:22 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      if current_user.author_of?(@answer) && @answer.save
Зачем тут проверка на автора? Как может текущий юзер быть не автором, если он и создает этот ответ? Как вообще это условие может не выполниться?

2017-10-25 15:22 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    render template: "questions/show"
При успешном создании - редирект, при не успешном - рендер.

2017-10-25 15:22 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new
Вот это как раз не имеет смысла. Если ты будешь делать редирект, то это все выполнится в show для вопроса. А если рендер, то как раз и нужно, чтобы в @answer был текущий невалидный ответ, чтобы можно было отобразить ошибки валидации

2017-10-25 15:22 UTC, vkurennov commented on app/views/answers/_form.html.haml
> += form_for @answer do |f|
Тебе, кстати, вообще эта форма не нужна, у тебя она в answers/_new

2017-10-25 15:22 UTC, vkurennov commented on app/views/answers/_new.html.haml
> += form_for [@question, @answer] do |f|
Вот здесь должен быть вывод ошибок валидации

2017-10-25 15:22 UTC, vkurennov commented on app/views/questions/_form.html.haml
> += form_for @question do |f|
И снова не исправлено

2017-10-25 15:24 UTC, vkurennov requested changes

2017-10-25 15:24 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Где тесты на метод `author_of?`

2017-10-25 16:43 UTC, AlkP commented on app/views/answers/_form.html.haml
> += form_for @answer do |f|
зачем?
зачем в каждой форме выводить свой алерт??? 
в чем сокральный смысл?

2017-10-25 16:49 UTC, AlkP commented on spec/acceptance/answer/create_answer_spec.rb
> +feature 'Create answer', %q{
все сделано.

2017-10-25 16:49 UTC, AlkP commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
тест есть. смотри. он и был. я не понимаю в чем проблема. пиши четко.

2017-10-25 16:50 UTC, AlkP commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
проверяется

2017-10-25 16:50 UTC, AlkP commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
сделано

2017-10-25 16:50 UTC, AlkP commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [ :index, :show ]
отредактировано

2017-10-31 09:34 UTC, closed without merging